/**
 * Comprehensive Mock Data for RAGDOL Real Estate Platform
 * Complete replacement for all database queries
 */

// ============= AGENTS MOCK DATA =============
export const mockAgents = [
  {
    id: 'agent-001',
    title: 'Senior Real Estate Consultant',
    office: 'Downtown Dubai Office',
    license_no: 'RERA-AG-12345',
    brokerage: 'Luxury Properties Dubai',
    bio: 'Expert in luxury properties with 15+ years of experience. Specializing in villas and penthouses.',
    areas: ['Downtown Dubai', 'Dubai Marina', 'Palm Jumeirah'],
    location: 'Dubai, UAE',
    whatsapp: '+971501234567',
    profile_image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80',
    rating: 4.8,
    review_count: 245,
    experience_years: 15,
    approved: true,
    verified: true,
  },
  {
    id: 'agent-002',
    title: 'Real Estate Specialist',
    office: 'Marina Mall Office',
    license_no: 'RERA-AG-12346',
    brokerage: 'Luxury Properties Dubai',
    bio: 'Passionate about matching clients with their dream homes. Expertise in residential and commercial properties.',
    areas: ['Dubai Marina', 'Emirates Hills', 'Business Bay'],
    location: 'Dubai, UAE',
    whatsapp: '+971509876543',
    profile_image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&q=80',
    rating: 4.9,
    review_count: 312,
    experience_years: 12,
    approved: true,
    verified: true,
  },
  {
    id: 'agent-003',
    title: 'Property Investment Advisor',
    office: 'Business Bay Office',
    license_no: 'RERA-AG-12347',
    brokerage: 'Luxury Properties Dubai',
    bio: 'Specializes in investment properties and off-plan developments. Fluent in English, Arabic, and Mandarin.',
    areas: ['Business Bay', 'Dubai Creek Harbour', 'Dubai South'],
    location: 'Dubai, UAE',
    whatsapp: '+971505555555',
    profile_image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&q=80',
    rating: 4.7,
    review_count: 189,
    experience_years: 10,
    approved: true,
    verified: true,
  },
  {
    id: 'agent-004',
    title: 'Luxury Villa Specialist',
    office: 'Emirates Hills Office',
    license_no: 'RERA-AG-12348',
    brokerage: 'Luxury Properties Dubai',
    bio: 'Dedicated to finding perfect luxury villas for discerning clients. Multi-property portfolio expertise.',
    areas: ['Emirates Hills', 'Arabian Ranches', 'Jumeirah'],
    location: 'Dubai, UAE',
    whatsapp: '+971504444444',
    profile_image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&q=80',
    rating: 4.9,
    review_count: 278,
    experience_years: 14,
    approved: true,
    verified: true,
  },
  {
    id: 'agent-005',
    title: 'Commercial Properties Expert',
    office: 'Downtown Office',
    license_no: 'RERA-AG-12349',
    brokerage: 'Luxury Properties Dubai',
    bio: 'Expert in commercial real estate, retail spaces, and business opportunities throughout Dubai.',
    areas: ['Business Bay', 'Downtown Dubai', 'JBR'],
    location: 'Dubai, UAE',
    whatsapp: '+971503333333',
    profile_image: 'https://images.unsplash.com/photo-1500636136919-5a2f53fcf973?w=400&q=80',
    rating: 4.6,
    review_count: 156,
    experience_years: 9,
    approved: true,
    verified: true,
  },
]

// ============= PROPERTIES MOCK DATA =============
export const mockProperties = [
  // Luxury Properties
  {
    id: 'prop-lux-001',
    title: 'Emirates Hills Luxury Mansion',
    slug: 'emirates-hills-luxury-mansion',
    type: 'villa',
    status: 'active',
    price: 55000000,
    currency: 'AED',
    beds: 7,
    baths: 9,
    sqft: 12000,
    image: 'https://images.pexels.com/photos/3729465/pexels-photo-3729465.jpeg?auto=compress&cs=tinysrgb&w=800',
    location: 'Emirates Hills, Dubai',
    area: 'Emirates Hills',
    city: 'Dubai',
    featured: true,
    published: true,
    description: 'Stunning luxury mansion in Emirates Hills with private golf course access and panoramic views.',
    agent_id: 'agent-001',
    video_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    parking: 'yes',
    propertyAge: '1-5',
    completion: 'ready',
    created_at: '2024-01-15T10:00:00Z',
  },
  {
    id: 'prop-lux-002',
    title: 'Palm Jumeirah Beachfront Estate',
    slug: 'palm-jumeirah-beachfront-estate',
    type: 'villa',
    status: 'sale',
    price: 42000000,
    currency: 'AED',
    beds: 6,
    baths: 7,
    sqft: 9500,
    image: 'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?auto=compress&cs=tinysrgb&w=800',
    location: 'Palm Jumeirah, Dubai',
    area: 'Palm Jumeirah',
    city: 'Dubai',
    featured: true,
    published: true,
    description: 'Exclusive beachfront villa on Palm Jumeirah with private marina access and stunning sea views.',
    agent_id: 'agent-002',
    video_url: 'https://www.youtube.com/watch?v=jNQXAC9IVRw',
    parking: 'yes',
    propertyAge: 'new',
    completion: 'ready',
  },
  {
    id: 'prop-lux-003',
    title: 'Dubai Marina Penthouse',
    slug: 'dubai-marina-penthouse',
    type: 'penthouse',
    status: 'sale',
    price: 18500000,
    currency: 'AED',
    beds: 4,
    baths: 5,
    sqft: 4200,
    image: 'https://images.pexels.com/photos/1350789/pexels-photo-1350789.jpeg?auto=compress&cs=tinysrgb&w=800',
    location: 'Dubai Marina, Dubai',
    area: 'Dubai Marina',
    city: 'Dubai',
    featured: true,
    published: true,
    description: 'Luxury penthouse with breathtaking marina and sea views from every room.',
    agent_id: 'agent-003',
    video_url: 'https://www.youtube.com/watch?v=ScMzIvxBSi4',
    parking: 'yes',
    propertyAge: '1-5',
    completion: 'ready',
  },
  // Regular Properties for Sale
  {
    id: 'prop-001',
    title: 'Luxury Penthouse in Downtown Dubai',
    slug: 'luxury-penthouse-downtown-dubai',
    type: 'penthouse',
    status: 'sale',
    price: 12500000,
    currency: 'AED',
    beds: 4,
    baths: 5,
    sqft: 4200,
    image: 'https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg?auto=compress&cs=tinysrgb&w=800',
    location: 'Downtown Dubai, Dubai',
    area: 'Downtown Dubai',
    city: 'Dubai',
    featured: true,
    published: true,
    description: 'Modern penthouse with floor-to-ceiling windows and Burj Khalifa views.',
    agent_id: 'agent-001',
    parking: 'yes',
    propertyAge: '5-10',
    completion: 'ready',
  },
  {
    id: 'prop-002',
    title: 'Modern Villa with Private Beach',
    slug: 'modern-villa-private-beach',
    type: 'villa',
    status: 'sale',
    price: 8900000,
    currency: 'AED',
    beds: 5,
    baths: 6,
    sqft: 5500,
    image: 'https://images.pexels.com/photos/1659438/pexels-photo-1659438.jpeg?auto=compress&cs=tinysrgb&w=800',
    location: 'Palm Jumeirah, Dubai',
    area: 'Palm Jumeirah',
    city: 'Dubai',
    featured: true,
    published: true,
    description: 'Contemporary villa with private beach access and resort-style amenities.',
    agent_id: 'agent-004',
    parking: 'yes',
    propertyAge: '1-5',
    completion: 'ready',
  },
  {
    id: 'prop-003',
    title: 'Contemporary Apartment Marina View',
    slug: 'contemporary-apartment-marina-view',
    type: 'apartment',
    status: 'sale',
    price: 3200000,
    currency: 'AED',
    beds: 3,
    baths: 3,
    sqft: 2100,
    image: 'https://images.pexels.com/photos/1350789/pexels-photo-1350789.jpeg?auto=compress&cs=tinysrgb&w=800',
    location: 'Dubai Marina, Dubai',
    area: 'Dubai Marina',
    city: 'Dubai',
    featured: true,
    published: true,
    description: 'Modern 3-bedroom apartment with stunning marina views and premium amenities.',
    agent_id: 'agent-002',
    parking: 'yes',
    propertyAge: 'new',
    completion: 'ready',
  },
  {
    id: 'prop-004',
    title: 'Studio Apartment Downtown Perfect Investment',
    slug: 'studio-apartment-downtown-investment',
    type: 'studio',
    status: 'sale',
    price: 950000,
    currency: 'AED',
    beds: 0,
    baths: 1,
    sqft: 420,
    image: 'https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg?auto=compress&cs=tinysrgb&w=800',
    location: 'Downtown Dubai, Dubai',
    area: 'Downtown Dubai',
    city: 'Dubai',
    featured: false,
    published: true,
    description: 'Perfect investment or starter property with excellent ROI potential.',
    agent_id: 'agent-003',
    parking: 'limited',
    propertyAge: 'new',
    completion: 'ready',
  },
  // Properties for Rent
  {
    id: 'prop-rent-001',
    title: 'Luxury Villa for Rent',
    slug: 'luxury-villa-for-rent',
    type: 'villa',
    status: 'rent',
    price: 250000,
    currency: 'AED',
    beds: 4,
    baths: 5,
    sqft: 4000,
    image: 'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?auto=compress&cs=tinysrgb&w=800',
    location: 'Emirates Hills, Dubai',
    area: 'Emirates Hills',
    city: 'Dubai',
    featured: true,
    published: true,
    description: 'Spacious luxury villa available for short or long-term rent.',
    agent_id: 'agent-001',
    parking: 'yes',
    propertyAge: '1-5',
    completion: 'ready',
  },
  {
    id: 'prop-rent-002',
    title: 'Modern 2BR Apartment Dubai Marina',
    slug: 'modern-2br-apartment-dubai-marina',
    type: 'apartment',
    status: 'rent',
    price: 150000,
    currency: 'AED',
    beds: 2,
    baths: 2,
    sqft: 1200,
    image: 'https://images.pexels.com/photos/1350789/pexels-photo-1350789.jpeg?auto=compress&cs=tinysrgb&w=800',
    location: 'Dubai Marina, Dubai',
    area: 'Dubai Marina',
    city: 'Dubai',
    featured: true,
    published: true,
    description: 'Modern apartment with all amenities and direct marina view.',
    agent_id: 'agent-002',
    parking: 'yes',
    propertyAge: 'new',
    completion: 'ready',
  },
  {
    id: 'prop-rent-003',
    title: 'Cozy 1BR Apartment Downtown',
    slug: 'cozy-1br-apartment-downtown',
    type: 'apartment',
    status: 'rent',
    price: 85000,
    currency: 'AED',
    beds: 1,
    baths: 1,
    sqft: 650,
    image: 'https://images.pexels.com/photos/1659438/pexels-photo-1659438.jpeg?auto=compress&cs=tinysrgb&w=800',
    location: 'Downtown Dubai, Dubai',
    area: 'Downtown Dubai',
    city: 'Dubai',
    featured: false,
    published: true,
    description: 'Affordable 1-bedroom apartment in heart of Downtown Dubai.',
    agent_id: 'agent-005',
    parking: 'limited',
    propertyAge: '5-10',
    completion: 'ready',
  },
]

// ============= PROJECTS MOCK DATA =============
export const mockProjects = [
  {
    id: 'proj-001',
    name: 'Emaar Beachfront Residences',
    slug: 'emaar-beachfront-residences',
    status: 'completed',
    developer_id: 'dev-001',
    city: 'Dubai',
    area: 'Dubai Marina',
    district: 'Dubai Marina',
    address: 'Marina Walk, Dubai Marina, Dubai',
    hero_image_url: 'https://images.pexels.com/photos/3729465/pexels-photo-3729465.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'Luxury beachfront residences with world-class amenities and direct beach access.',
    starting_price: 2500000,
    min_price: 1800000,
    max_price: 8500000,
    currency: 'AED',
    total_units: 500,
    available_units: 45,
    amenities: ['Beach Access', 'Swimming Pools', 'Gym', 'Spa', 'Restaurants', 'Shopping'],
    featured: true,
    published: true,
  },
  {
    id: 'proj-002',
    name: 'Downtown Residences Phase 2',
    slug: 'downtown-residences-phase-2',
    status: 'in-progress',
    developer_id: 'dev-002',
    city: 'Dubai',
    area: 'Downtown Dubai',
    district: 'Downtown',
    address: 'Sheikh Zayed Road, Downtown Dubai',
    hero_image_url: 'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'New phase of premium residences in the heart of Downtown Dubai.',
    starting_price: 1900000,
    min_price: 1200000,
    max_price: 6500000,
    currency: 'AED',
    total_units: 300,
    available_units: 120,
    amenities: ['Burj Khalifa View', 'Shopping Mall', 'Parks', 'Schools', 'Healthcare'],
    featured: true,
    published: true,
  },
  {
    id: 'proj-003',
    name: 'Dubai Hills Estate Villas',
    slug: 'dubai-hills-estate-villas',
    status: 'completed',
    developer_id: 'dev-001',
    city: 'Dubai',
    area: 'Dubai Hills Estate',
    district: 'Dubai Hills',
    address: 'Dubai Hills Estate, Dubai',
    hero_image_url: 'https://images.pexels.com/photos/1350789/pexels-photo-1350789.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'Exclusive villa community with golf course, parks, and luxury amenities.',
    starting_price: 3500000,
    min_price: 2800000,
    max_price: 12000000,
    currency: 'AED',
    total_units: 800,
    available_units: 80,
    amenities: ['Golf Course', 'Parks', 'Community Center', 'Schools', 'Retail'],
    featured: true,
    published: true,
  },
]

// ============= DEVELOPERS MOCK DATA =============
export const mockDevelopers = [
  {
    id: 'dev-001',
    name: 'Emaar Properties',
    logo_url: 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjEwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSIjZGRkIi8+PHRleHQgeD0iNTAlIiB5PSI1MCUiIGZvbnQtZmFtaWx5PSJBcmlhbCwgc2Fucy1zZXJpZiIgZm9udC1zaXplPSIxNCIgZmlsbD0iIzk5OSIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZHk9Ii4zZW0iPkVtYWFyPC90ZXh0Pjwvc3ZnPg==',
    website: 'https://www.emaar.com',
    description: 'Leading real estate developer in UAE with iconic projects across Dubai.',
    contact_email: 'info@emaar.com',
    founded_year: 1997,
    total_projects: 150,
    active_projects: 25,
    verified: true,
  },
  {
    id: 'dev-002',
    name: 'Damac Properties',
    logo_url: 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjEwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSIjZGRkIi8+PHRleHQgeD0iNTAlIiB5PSI1MCUiIGZvbnQtZmFtaWx5PSJBcmlhbCwgc2Fucy1zZXJpZiIgZm9udC1zaXplPSIxNCIgZmlsbD0iIzk5OSIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZHk9Ii4zZW0iPkRhbWFjPC90ZXh0Pjwvc3ZnPg==',
    website: 'https://www.damacproperties.com',
    description: 'Luxury real estate developer known for ultra-premium residences.',
    contact_email: 'sales@damacproperties.com',
    founded_year: 2002,
    total_projects: 80,
    active_projects: 15,
    verified: true,
  },
]

// ============= MOCK ENQUIRIES =============
export const mockEnquiries = [
  {
    id: 'enq-001',
    property_id: 'prop-001',
    agent_id: 'agent-001',
    user_id: 'user-001',
    status: 'pending',
    priority: 'high',
    name: 'John Smith',
    email: 'john.smith@example.com',
    phone: '+971501234567',
    message: 'Very interested in this penthouse. Would like to schedule a viewing.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'enq-002',
    property_id: 'prop-002',
    agent_id: 'agent-004',
    user_id: 'user-002',
    status: 'accepted',
    priority: 'medium',
    name: 'Sarah Johnson',
    email: 'sarah.j@example.com',
    phone: '+971509876543',
    message: 'Interested in villa. Can we discuss pricing?',
    created_at: new Date().toISOString(),
  },
]

// ============= MOCK USERS =============
export const mockUsers = [
  {
    id: 'user-001',
    email: 'customer@ragdol.com',
    full_name: 'John Smith',
    role: 'customer',
    phone: '+971501234567',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200',
    created_at: new Date().toISOString(),
  },
  {
    id: 'user-002',
    email: 'john_doe@example.com',
    full_name: 'John Doe',
    role: 'customer',
    phone: '+971509876543',
    avatar_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200',
    created_at: new Date().toISOString(),
  },
  {
    id: 'user-003',
    email: 'sarah_smith@example.com',
    full_name: 'Sarah Smith',
    role: 'customer',
    phone: '+971507654321',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200',
    created_at: new Date().toISOString(),
  },
  {
    id: 'admin-001',
    email: 'admin@ragdol.com',
    full_name: 'Admin User',
    role: 'admin',
    phone: '+97144444444',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200',
    created_at: new Date().toISOString(),
  },
  {
    id: 'admin-002',
    email: 'superadmin@ragdol.com',
    full_name: 'Super Admin',
    role: 'admin',
    phone: '+97155555555',
    avatar_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200',
    created_at: new Date().toISOString(),
  },
  {
    id: 'admin-003',
    email: 'manager@ragdol.com',
    full_name: 'Manager User',
    role: 'admin',
    phone: '+97166666666',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200',
    created_at: new Date().toISOString(),
  },
  {
    id: 'agent-001',
    email: 'agent@ragdol.com',
    full_name: 'Ahmed Hassan',
    role: 'agent',
    phone: '+971501234567',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200',
    created_at: new Date().toISOString(),
  },
]

// ============= MOCK DASHBOARD METRICS =============
export const mockDashboardMetrics = {
  totalProperties: mockProperties.length,
  totalAgents: mockAgents.length,
  totalProjects: mockProjects.length,
  totalEnquiries: mockEnquiries.length,
  propertiesForSale: mockProperties.filter((p) => p.status === 'sale').length,
  propertiesForRent: mockProperties.filter((p) => p.status === 'rent').length,
  featuredProperties: mockProperties.filter((p) => p.featured).length,
  avgPropertyPrice:
    mockProperties.filter((p) => p.status === 'sale').reduce((sum, p) => sum + p.price, 0) /
    mockProperties.filter((p) => p.status === 'sale').length,
}

// ============= MOCK BLOG POSTS =============
export const mockBlogPosts = [
  {
    id: 'blog-001',
    title: 'The Ultimate Guide to Buying Property in Dubai',
    slug: 'ultimate-guide-buying-property-dubai',
    excerpt: 'Learn everything you need to know before making your property investment in Dubai.',
    content: 'Lorem ipsum dolor sit amet...',
    image: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80',
    author: 'Real Estate Expert',
    published_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    category: 'Guides',
  },
  {
    id: 'blog-002',
    title: 'Dubai Real Estate Market Trends 2024',
    slug: 'dubai-real-estate-market-trends-2024',
    excerpt: 'Discover the latest trends shaping the Dubai real estate market.',
    content: 'Lorem ipsum dolor sit amet...',
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80',
    author: 'Market Analyst',
    published_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    category: 'Market Update',
  },
]

// ============= MOCK FAQs =============
export const mockFAQs = [
  {
    id: 'faq-001',
    question: 'How do I start my property search?',
    answer: 'You can browse our extensive property listings using our search filters. Our agents are also available to help personalize your search.',
    category: 'Getting Started',
  },
  {
    id: 'faq-002',
    question: 'What are the costs involved in buying property in Dubai?',
    answer: 'Main costs include property price, registration fees (4% of property value), real estate agent commission, and legal fees.',
    category: 'Financial',
  },
  {
    id: 'faq-003',
    question: 'Can foreigners own property in Dubai?',
    answer: 'Yes, foreigners can own property in designated freehold areas. Our agents can guide you on eligible zones.',
    category: 'Legal',
  },
]

// ============= JOBS MOCK DATA =============
export const mockJobs = [
  {
    id: 'job-001',
    title: 'Senior Real Estate Consultant',
    department: 'Sales',
    location: 'Dubai, UAE',
    type: 'Full-time',
    description: 'Join our elite team as a Senior Real Estate Consultant. Work with Dubai\'s most exclusive properties and high-net-worth clients.',
    requirements: [
      '5+ years of luxury real estate experience',
      'Proven track record of $50M+ in annual sales',
      'RERA certification required',
      'Fluent English, Arabic preferred',
      'Strong network in Dubai\'s luxury market'
    ],
    salary: 'Commission-based + Performance Bonuses',
    posted_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'active'
  },
  {
    id: 'job-002',
    title: 'Property Consultant',
    department: 'Sales',
    location: 'Dubai, UAE',
    type: 'Full-time',
    description: 'Exciting opportunity for an ambitious real estate professional to join our growing team. Focus on residential and commercial properties.',
    requirements: [
      '2+ years of real estate experience',
      'RERA certification or in progress',
      'Excellent communication skills',
      'Self-motivated and target-driven',
      'Valid UAE residence visa'
    ],
    salary: 'Commission-based + Base Salary',
    posted_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'active'
  },
  {
    id: 'job-003',
    title: 'Marketing Manager',
    department: 'Marketing',
    location: 'Dubai, UAE',
    type: 'Full-time',
    description: 'Lead our digital marketing efforts and brand positioning in the luxury real estate market. Drive growth through innovative marketing strategies.',
    requirements: [
      '4+ years of digital marketing experience',
      'Experience in luxury/real estate industry preferred',
      'Strong social media and content creation skills',
      'Analytics and SEO expertise',
      'Creative portfolio showcasing luxury brand work'
    ],
    salary: 'AED 25,000 - 35,000 + Benefits',
    posted_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'active'
  },
  {
    id: 'job-004',
    title: 'Real Estate Administrator',
    department: 'Operations',
    location: 'Dubai, UAE',
    type: 'Full-time',
    description: 'Support our operations team with administrative tasks, client coordination, and database management. Perfect entry-level position in luxury real estate.',
    requirements: [
      'Bachelor\'s degree in Business or related field',
      'Strong organizational and communication skills',
      'Proficiency in Microsoft Office and CRM systems',
      'Attention to detail and client service orientation',
      'Interest in real estate industry'
    ],
    salary: 'AED 12,000 - 18,000 + Benefits',
    posted_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'active'
  }
]

// ============= MOCK APPLICATIONS =============
export const mockApplications = [
  {
    id: 'app-001',
    job_id: 'job-001',
    job_title: 'Senior Real Estate Agent',
    full_name: 'John Doe',
    email: 'john.doe@example.com',
    phone: '+971 50 123 4567',
    nationality: 'British',
    experience: '5 years',
    linkedin: 'https://linkedin.com/in/johndoe',
    resume_url: '#',
    cover_letter: 'I am very interested in this position...',
    status: 'pending',
    applied_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'app-002',
    job_id: 'job-002',
    job_title: 'Property Consultant',
    full_name: 'Jane Smith',
    email: 'jane.smith@example.com',
    phone: '+971 55 987 6543',
    nationality: 'Canadian',
    experience: '2 years',
    linkedin: 'https://linkedin.com/in/janesmith',
    resume_url: '#',
    cover_letter: 'I have a passion for real estate...',
    status: 'reviewed',
    applied_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

// ============= MOCK CATEGORIES =============
export const mockCategories = [
  {
    id: 'cat-001',
    name: 'Residential',
    slug: 'residential',
    description: 'Houses, apartments, and residential properties',
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-002',
    name: 'Commercial',
    slug: 'commercial',
    description: 'Office spaces, retail, and commercial properties',
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-003',
    name: 'Luxury',
    slug: 'luxury',
    description: 'High-end luxury properties and estates',
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-004',
    name: 'Investment',
    slug: 'investment',
    description: 'Properties suitable for investment and rental income',
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-005',
    name: 'Off-Plan',
    slug: 'off-plan',
    description: 'Upcoming developments and off-plan properties',
    created_at: new Date().toISOString(),
  },
]

// ============= UTILITY FUNCTIONS =============
export function getTopAgents(limit = 4) {
  return mockAgents
    .sort((a, b) => (b.rating || 0) - (a.rating || 0))
    .slice(0, limit)
    .map(agent => ({
      id: agent.id,
      title: agent.title,
      bio: agent.bio,
      experience_years: agent.experience_years,
      rating: agent.rating,
      review_count: agent.review_count,
      profile_image: agent.profile_image,
      profiles: null, // Not needed for simplified interface
    }))
}

// ============= CUSTOMER MOCK DATA =============
export const mockSavedProperties = [
  {
    id: 'saved-001',
    user_id: 'user-001', // Mock user ID
    property_id: 'prop-lux-001',
    saved_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'saved-002',
    user_id: 'user-001',
    property_id: 'prop-lux-002',
    saved_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'saved-003',
    user_id: 'user-001',
    property_id: 'prop-001',
    saved_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

export const mockValuations = [
  {
    id: 'val-001',
    user_id: 'user-001',
    property_type: 'villa',
    location: 'Dubai Marina',
    size: '2500',
    bedrooms: '4',
    bathrooms: '5',
    year_built: '2020',
    condition: 'excellent',
    additional_features: 'Private pool, garden, parking',
    urgency: 'medium',
    contact_method: 'email',
    status: 'completed',
    estimated_value: '18500000',
    currency: 'AED',
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    completed_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'val-002',
    user_id: 'user-001',
    property_type: 'penthouse',
    location: 'Downtown Dubai',
    size: '1800',
    bedrooms: '3',
    bathrooms: '4',
    year_built: '2019',
    condition: 'good',
    additional_features: 'Burj Khalifa view, terrace',
    urgency: 'high',
    contact_method: 'phone',
    status: 'in_progress',
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

export const mockCustomerEnquiries = [
  {
    id: 'enq-001',
    user_id: 'user-001',
    property_id: 'prop-lux-001',
    name: 'John Smith',
    email: 'john.smith@example.com',
    phone: '+971501234567',
    message: 'I am interested in this property. Can you provide more details about the neighborhood and available financing options?',
    status: 'responded',
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    responded_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'enq-002',
    user_id: 'user-001',
    property_id: 'prop-lux-002',
    name: 'John Smith',
    email: 'john.smith@example.com',
    phone: '+971501234567',
    message: 'Is this property still available? I would like to schedule a viewing this weekend.',
    status: 'pending',
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'enq-003',
    user_id: 'user-001',
    property_id: 'prop-001',
    name: 'John Smith',
    email: 'john.smith@example.com',
    phone: '+971501234567',
    message: 'Could you please send me the floor plan and more interior photos?',
    status: 'responded',
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    responded_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
]
