import Link from 'next/link'
import Image from 'next/image'
import { StarIcon, PhoneIcon, EnvelopeIcon } from '@heroicons/react/24/outline'
import { StarIcon as StarSolid } from '@heroicons/react/24/solid'
import AgentListClient from '@/components/AgentListClient'
import { Database } from '@/lib/database.types'

type AgentRow = Database['public']['Tables']['agents']['Row']
type ProfileRow = Database['public']['Tables']['profiles']['Row']
type AgentWithProfile = AgentRow & { profiles?: ProfileRow | null }

// Mock agents data
const mockAgents: AgentWithProfile[] = [
  {
    id: 'agent-1',
    title: 'Senior Real Estate Agent',
    bio: 'Specializing in luxury properties in Dubai Marina and Downtown Dubai',
    experience_years: 8,
    rating: 4.8,
    review_count: 89,
    total_sales: 450000000,
    profile_image: 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&q=80',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    office: 'Dubai Downtown Office',
    license_no: '123456789',
    approved: true,
    social: { linkedin: 'https://linkedin.com/in/sarah-ahmed', instagram: '@sarah_realestate_dubai' },
    brokerage: 'RAGDOL Real Estate',
    certifications: ['RERA Certified', 'Luxury Property Specialist'],
    commission_rate: 2.5,
    languages: ['English', 'Arabic'],
    areas: ['Downtown Dubai', 'Dubai Marina', 'Palm Jumeirah', 'Emirates Hills'],
    verified: true,
    user_id: 'user-1',
    whatsapp: '+971501234567',
    linkedin_url: 'https://linkedin.com/in/sarah-ahmed',
    instagram_handle: '@sarah_realestate_dubai',
    website_url: 'https://sarah-ahmed.ragdol.ae',
    location: 'Dubai, UAE',
    profile_images: ['https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&q=80'],
    specializations: ['Luxury Properties', 'Investment Properties', 'Off-Plan'],
    telegram: null,
    profiles: {
      id: 'user-1',
      full_name: 'Sarah Ahmed',
      avatar_url: 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&q=80',
      phone: '+971 50 123 4567',
      role: 'agent',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      email_verified: true,
      phone_verified: true,
      last_login: new Date().toISOString(),
      login_count: 245,
      location: 'Dubai, UAE',
      bio: 'Real estate agent with 8+ years experience',
      preferences: { notifications: true, language: 'en' },
      social_links: { linkedin: 'https://linkedin.com/in/sarah-ahmed' }
    }
  },
  {
    id: 'agent-2',
    title: 'Luxury Property Specialist',
    bio: 'Expert in Palm Jumeirah and Emirates Hills properties',
    experience_years: 10,
    rating: 4.9,
    review_count: 120,
    total_sales: 625000000,
    profile_image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    office: 'Palm Jumeirah Office',
    license_no: '987654321',
    approved: true,
    social: { linkedin: 'https://linkedin.com/in/ahmed-hassan', instagram: '@ahmed_luxury_dubai' },
    brokerage: 'RAGDOL Real Estate',
    certifications: ['RERA Certified', 'Luxury Property Expert', 'Investment Advisor'],
    commission_rate: 2.75,
    languages: ['English', 'Arabic', 'French'],
    areas: ['Palm Jumeirah', 'Emirates Hills', 'Arabian Ranches', 'Emirates Living'],
    verified: true,
    user_id: 'user-2',
    whatsapp: '+971501234568',
    linkedin_url: 'https://linkedin.com/in/ahmed-hassan',
    instagram_handle: '@ahmed_luxury_dubai',
    website_url: 'https://ahmed-hassan.ragdol.ae',
    location: 'Dubai, UAE',
    profile_images: ['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80'],
    specializations: ['Luxury Villas', 'Waterfront Properties', 'Custom Developments'],
    telegram: null,
    profiles: {
      id: 'user-2',
      full_name: 'Ahmed Hassan',
      avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80',
      phone: '+971 50 234 5678',
      role: 'agent',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      email_verified: true,
      phone_verified: true,
      last_login: new Date().toISOString(),
      login_count: 312,
      location: 'Dubai, UAE',
      bio: 'Senior luxury property specialist',
      preferences: { notifications: true, language: 'en' },
      social_links: { linkedin: 'https://linkedin.com/in/ahmed-hassan' }
    }
  },
  {
    id: 'agent-3',
    title: 'Commercial Real Estate Broker',
    bio: 'Specializing in commercial spaces and investment opportunities',
    experience_years: 9,
    rating: 4.7,
    review_count: 76,
    total_sales: 380000000,
    profile_image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&q=80',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    office: 'Business Bay Office',
    license_no: '456789123',
    approved: true,
    social: { linkedin: 'https://linkedin.com/in/fatima-khan', instagram: '@fatima_commercial_dubai' },
    brokerage: 'RAGDOL Real Estate',
    certifications: ['RERA Certified', 'Commercial Real Estate Expert'],
    commission_rate: 3.0,
    languages: ['English', 'Arabic', 'Urdu'],
    areas: ['Business Bay', 'Dubai Marina', 'Downtown Dubai', 'DIFC'],
    verified: true,
    user_id: 'user-3',
    whatsapp: '+971501234569',
    linkedin_url: 'https://linkedin.com/in/fatima-khan',
    instagram_handle: '@fatima_commercial_dubai',
    website_url: 'https://fatima-khan.ragdol.ae',
    location: 'Dubai, UAE',
    profile_images: ['https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&q=80'],
    specializations: ['Commercial Properties', 'Investment Opportunities', 'Office Leasing'],
    telegram: null,
    profiles: {
      id: 'user-3',
      full_name: 'Fatima Khan',
      avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&q=80',
      phone: '+971 50 345 6789',
      role: 'agent',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      email_verified: true,
      phone_verified: true,
      last_login: new Date().toISOString(),
      login_count: 198,
      location: 'Dubai, UAE',
      bio: 'Commercial real estate specialist',
      preferences: { notifications: true, language: 'en' },
      social_links: { linkedin: 'https://linkedin.com/in/fatima-khan' }
    }
  },
  {
    id: 'agent-4',
    title: 'Investment Property Advisor',
    bio: 'Expert in property investment strategies and portfolio management',
    experience_years: 7,
    rating: 4.6,
    review_count: 95,
    total_sales: 320000000,
    profile_image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&q=80',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    office: 'Jumeirah Village Circle Office',
    license_no: '789123456',
    approved: true,
    social: { linkedin: 'https://linkedin.com/in/maria-rodriguez', instagram: '@maria_investment_dubai' },
    brokerage: 'RAGDOL Real Estate',
    certifications: ['RERA Certified', 'Investment Property Specialist'],
    commission_rate: 2.25,
    languages: ['English', 'Arabic', 'Hindi'],
    areas: ['Jumeirah Village Circle', 'Dubai Silicon Oasis', 'Dubai Festival City'],
    verified: true,
    user_id: 'user-4',
    whatsapp: '+971501234570',
    linkedin_url: 'https://linkedin.com/in/maria-rodriguez',
    instagram_handle: '@maria_investment_dubai',
    website_url: 'https://maria-rodriguez.ragdol.ae',
    location: 'Dubai, UAE',
    profile_images: ['https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&q=80'],
    specializations: ['Investment Properties', 'Portfolio Management', 'Rental Yields'],
    telegram: null,
    profiles: {
      id: 'user-4',
      full_name: 'Maria Rodriguez',
      avatar_url: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&q=80',
      phone: '+971 50 456 7890',
      role: 'agent',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      email_verified: true,
      phone_verified: true,
      last_login: new Date().toISOString(),
      login_count: 167,
      location: 'Dubai, UAE',
      bio: 'Investment property advisor',
      preferences: { notifications: true, language: 'en' },
      social_links: { linkedin: 'https://linkedin.com/in/maria-rodriguez' }
    }
  },
  {
    id: 'agent-5',
    title: 'Off-Plan Development Specialist',
    bio: 'Specializing in new developments and off-plan property investments',
    experience_years: 6,
    rating: 4.8,
    review_count: 82,
    total_sales: 280000000,
    profile_image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&q=80',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    office: 'Dubai Festival City Office',
    license_no: '321654987',
    approved: true,
    social: { linkedin: 'https://linkedin.com/in/david-chen', instagram: '@david_offplan_dubai' },
    brokerage: 'RAGDOL Real Estate',
    certifications: ['RERA Certified', 'Off-Plan Specialist'],
    commission_rate: 2.5,
    languages: ['English', 'Arabic'],
    areas: ['Dubai Festival City', 'Al Barsha', 'Dubai Silicon Oasis'],
    verified: true,
    user_id: 'user-5',
    whatsapp: '+971501234571',
    linkedin_url: 'https://linkedin.com/in/david-chen',
    instagram_handle: '@david_offplan_dubai',
    website_url: 'https://david-chen.ragdol.ae',
    location: 'Dubai, UAE',
    profile_images: ['https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&q=80'],
    specializations: ['Off-Plan Properties', 'New Developments', 'Investment Opportunities'],
    telegram: null,
    profiles: {
      id: 'user-5',
      full_name: 'David Chen',
      avatar_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&q=80',
      phone: '+971 50 567 8901',
      role: 'agent',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      email_verified: true,
      phone_verified: true,
      last_login: new Date().toISOString(),
      login_count: 134,
      location: 'Dubai, UAE',
      bio: 'Off-plan development specialist',
      preferences: { notifications: true, language: 'en' },
      social_links: { linkedin: 'https://linkedin.com/in/david-chen' }
    }
  },
  {
    id: 'agent-6',
    title: 'Rental Property Specialist',
    bio: 'Expert in long-term rentals and property management',
    experience_years: 11,
    rating: 4.9,
    review_count: 156,
    total_sales: 420000000,
    profile_image: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=400&q=80',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    office: 'Dubai Marina Office',
    license_no: '654987321',
    approved: true,
    social: { linkedin: 'https://linkedin.com/in/elena-petrova', instagram: '@elena_rental_dubai' },
    brokerage: 'RAGDOL Real Estate',
    certifications: ['RERA Certified', 'Property Management Expert'],
    commission_rate: 1.5,
    languages: ['English', 'Arabic', 'Russian'],
    areas: ['Dubai Marina', 'Jumeirah Beach Residence', 'Palm Jumeirah'],
    verified: true,
    user_id: 'user-6',
    whatsapp: '+971501234572',
    linkedin_url: 'https://linkedin.com/in/elena-petrova',
    instagram_handle: '@elena_rental_dubai',
    website_url: 'https://elena-petrova.ragdol.ae',
    location: 'Dubai, UAE',
    profile_images: ['https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=400&q=80'],
    specializations: ['Rental Properties', 'Property Management', 'Long-term Leasing'],
    telegram: null,
    profiles: {
      id: 'user-6',
      full_name: 'Elena Petrova',
      avatar_url: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=400&q=80',
      phone: '+971 50 678 9012',
      role: 'agent',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      email_verified: true,
      phone_verified: true,
      last_login: new Date().toISOString(),
      login_count: 289,
      location: 'Dubai, UAE',
      bio: 'Rental property specialist',
      preferences: { notifications: true, language: 'en' },
      social_links: { linkedin: 'https://linkedin.com/in/elena-petrova' }
    }
  },
  {
    id: 'agent-7',
    title: 'Luxury Villa Specialist',
    bio: 'Exclusive villa properties and waterfront estates expert',
    experience_years: 12,
    rating: 4.9,
    review_count: 178,
    total_sales: 890000000,
    profile_image: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&q=80',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    office: 'Emirates Hills Office',
    license_no: '987321654',
    approved: true,
    social: { linkedin: 'https://linkedin.com/in/isabella-rossi', instagram: '@isabella_luxury_dubai' },
    brokerage: 'RAGDOL Real Estate',
    certifications: ['RERA Certified', 'Luxury Property Specialist', 'Villa Expert'],
    commission_rate: 3.0,
    languages: ['English', 'Arabic', 'French', 'Italian'],
    areas: ['Emirates Hills', 'Palm Jumeirah', 'Jumeirah', 'Dubai Hills Estate'],
    verified: true,
    user_id: 'user-7',
    whatsapp: '+971501234573',
    linkedin_url: 'https://linkedin.com/in/isabella-rossi',
    instagram_handle: '@isabella_luxury_dubai',
    website_url: 'https://isabella-rossi.ragdol.ae',
    location: 'Dubai, UAE',
    profile_images: ['https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&q=80'],
    specializations: ['Luxury Villas', 'Waterfront Properties', 'Exclusive Estates'],
    telegram: null,
    profiles: {
      id: 'user-7',
      full_name: 'Isabella Rossi',
      avatar_url: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&q=80',
      phone: '+971 50 789 0123',
      role: 'agent',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      email_verified: true,
      phone_verified: true,
      last_login: new Date().toISOString(),
      login_count: 345,
      location: 'Dubai, UAE',
      bio: 'Luxury villa specialist',
      preferences: { notifications: true, language: 'en' },
      social_links: { linkedin: 'https://linkedin.com/in/isabella-rossi' }
    }
  },
  {
    id: 'agent-8',
    title: 'Commercial Property Broker',
    bio: 'Office spaces, retail properties, and commercial investments',
    experience_years: 9,
    rating: 4.7,
    review_count: 134,
    total_sales: 560000000,
    profile_image: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&q=80',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    office: 'Business Bay Office',
    license_no: '456123789',
    approved: true,
    social: { linkedin: 'https://linkedin.com/in/ahmed-mansoori', instagram: '@ahmed_commercial_dubai' },
    brokerage: 'RAGDOL Real Estate',
    certifications: ['RERA Certified', 'Commercial Broker', 'Investment Specialist'],
    commission_rate: 2.75,
    languages: ['English', 'Arabic', 'Urdu'],
    areas: ['Business Bay', 'DIFC', 'Dubai Media City', 'Dubai Internet City'],
    verified: true,
    user_id: 'user-8',
    whatsapp: '+971501234574',
    linkedin_url: 'https://linkedin.com/in/ahmed-mansoori',
    instagram_handle: '@ahmed_commercial_dubai',
    website_url: 'https://ahmed-mansoori.ragdol.ae',
    location: 'Dubai, UAE',
    profile_images: ['https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&q=80'],
    specializations: ['Commercial Properties', 'Office Spaces', 'Retail Properties'],
    telegram: null,
    profiles: {
      id: 'user-8',
      full_name: 'Ahmed Al-Mansoori',
      avatar_url: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&q=80',
      phone: '+971 50 890 1234',
      role: 'agent',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      email_verified: true,
      phone_verified: true,
      last_login: new Date().toISOString(),
      login_count: 223,
      location: 'Dubai, UAE',
      bio: 'Commercial property broker',
      preferences: { notifications: true, language: 'en' },
      social_links: { linkedin: 'https://linkedin.com/in/ahmed-mansoori' }
    }
  }
]

async function getAgents() {
  // Always return mock data
  return mockAgents
}

export default async function AgentsPage() {
  const agents = await getAgents()
  return (
    <AgentListClient agents={agents.map((a) => ({
      id: a.id,
      profile_image: a.profile_image,
      profile: a.profiles ? { full_name: a.profiles.full_name, avatar_url: a.profiles.avatar_url } : undefined,
      title: a.title || undefined,
      experience_years: a.experience_years || undefined,
      properties: a.total_sales ? Math.floor(a.total_sales / 10000000) : 12, // Mocking property count for UI
      rating: a.rating || undefined,
      review_count: a.review_count || undefined,
      specializations: a.specializations || undefined,
    }))} />
  )
}
